[package]
name = "ss13-atmos"
version = "0.1.0"
authors = ["Putnam <putnam3145@gmail.com>"]

[lib]
name = "atmos"
crate-type = ["cdylib"]

[dependencies]
float-ord = "0.2.0"
phf = { version = "0.8", features = ["macros"] }

[profile.release]
opt-level = 3
lto = true